### ISSUE TITLE
Tensorflow Problem Maybe

### ISSUE THREAD

**Issue by sandipan-basak** [YunYang1994/tensorflow-yolov3#112]
2019-04-17 19:51:09.443819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15176 MB memory) -> physical GPU (device: 0, name: Quadro P5000, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-04-17 19:51:36.039628: W tensorflow/core/framework/op_kernel.cc:1261] Unknown: IndexError: index 51 is out of bounds for axis 3 with size 8
Traceback (most recent call last):

  File "/home/sandipanb/.local/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/swdata1/sandipanb/YunYang1994/YinYang1994/tensorflow-yolov3/core/dataset.py", line 173, in preprocess_true_boxes
    y_true[l][j, i, k, 5+c] = 1.

IndexError: index 51 is out of bounds for axis 3 with size 8

**Comment by fengxiuyaun** [comment]
your box may be wrong

**Comment by broliao** [comment]
you label dataset should be wrong
