### ISSUE TITLE
测试demo未通过

### ISSUE THREAD

**Issue by CVerRobin** [YunYang1994/tensorflow-yolov3#127]
Traceback (most recent call last):
  File "H:/yolov3-demo/tensorflow-yolov3/video_demo.py", line 44, in <module>
    image = utils.draw_boxes(image, boxes, scores, labels, classes, (IMAGE_H, IMAGE_W), show=False)
  File "H\yolov3-demo\tensorflow-yolov3\core\utils.py", line 171, in draw_boxes
    for i in range(len(labels)): # for each bounding box, do:
TypeError: object of type 'Tensor' has no len()
您好，我的报这个错，按照教程重新来了一遍也不行

**Comment by YunYang1994** [comment]
你可以改变阈值看看
