### ISSUE TITLE
训练自己数据集遇到错误

### ISSUE THREAD

**Issue by GaffeyFF** [YunYang1994/tensorflow-yolov3#138]
不知道是哪里的list超出了范围
2019-05-10 16:37:57.395048: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.406620: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.407144: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.407656: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.416684: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.417915: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.422429: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](stack)]]
2019-05-10 16:37:57.427843: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.428245: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.428871: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.431185: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
2019-05-10 16:37:57.441301: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: IndexError: list index out of range
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](stack)]]
	 [[Node: cond/IteratorGetNext = IteratorGetNext[output_shapes=[[?,608,608,3], <unknown>, <unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](cond/IteratorGetNext/Switch:1)]]
	 [[Node: cond/IteratorGetNext/_535 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_542_cond/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quick_train.py", line 84, in <module>
    run_items = sess.run([train_op, write_op, y_pred, y_true] + loss, feed_dict={is_training:True})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: IndexError: list index out of range
	 [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0"](stack)]]
	 [[Node: cond/IteratorGetNext = IteratorGetNext[output_shapes=[[?,608,608,3], <unknown>, <unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](cond/IteratorGetNext/Switch:1)]]
	 [[Node: cond/IteratorGetNext/_535 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_542_cond/IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by Ragas99205** [comment]
@GaffeyFF did you solve it? I am getting the same error.

**Comment by GaffeyFF** [comment]
yeah , the anchor number set to 9 ,no problem

**Comment by wyukai** [comment]
我的anchor设置是9啊，还是出现了这个错误

**Comment by GaffeyFF** [comment]
> 我的anchor设置是9啊，还是出现了这个错误

 python3 convert_weight.py --convert 和训练的时候尺寸什么参数是不是都是一样的

**Comment by ClayZhang0403** [comment]
我有一个基于VOC格式的数据集 目录结构是
VOC
——VOCdevkit
————VOC2019
——————Annotations
————————一堆xml
——————JPEGImages
————————一堆图片
——————ImageSets
——————SegmentationClass
——————SegmentationObject
想请问大家一下怎么用tensorflow训练 本人小白，可能比较愚钝 还尽可能说到位一下 谢谢大家
