### ISSUE TITLE
运行 convert_weight.py出错  KeyError: u'NonMaxSuppressionV3'

### ISSUE THREAD

**Issue by zhanglsky** [YunYang1994/tensorflow-yolov3#146]
错误出现在加载meta文件上，第27行 load = tf.train.import_meta_graph(meta_graph)
是模型有变化导致的吗？有没有同样遇到该问题的好心人解答一下啊，十分感激～

**Comment by CNUyue** [comment]
我也是运行这个出错，不过不一样 
$python convert_weight.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_weight.py", line 15, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by zhanglsky** [comment]
> 我也是运行这个出错，不过不一样
> $python convert_weight.py
> Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "/usr/lib/python3.5/imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "convert_weight.py", line 15, in
> import tensorflow as tf
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/**init**.py", line 24, in
> from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/**init**.py", line 49, in
> from tensorflow.python import pywrap_tensorflow
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in
> raise ImportError(msg)
> ImportError: Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "/usr/lib/python3.5/imp.py", line 242, in load_module
> return load_dynamic(name, filename, file)
> File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
> return _load(spec)
> ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions. Include the entire stack trace
> above this error message when asking for help.

感谢你的建议，我再试试，谢谢！

**Comment by waynamigo** [comment]
版本问题。。

**Comment by hiSirius** [comment]
> 错误出现在加载meta文件上，第27行 load = tf.train.import_meta_graph(meta_graph)
> 是模型有变化导致的吗？有没有同样遇到该问题的好心人解答一下啊，十分感激～

我也有同样的问题。话说，你的问题解决了吗？如果解决了的话，给我参考下。谢谢

**Comment by xenron** [comment]
@zhanglsky 
The reason:
Author froze the graph using 1.9+, maybe you tried to use it using 1.8 or lower (accidentally).
If you use 1.9 for inference, I think there will be no problem.

recommend:
pip install -r ./docs/requirements.txt
