### ISSUE TITLE
Problem in testing image_demo.py

### ISSUE THREAD

**Issue by ClayZhang0403** [YunYang1994/tensorflow-yolov3#160]
when I use image_demo.py ,but wrong by this follow :
Traceback (most recent call last):
  File "image_demo.py", line 33, in <module>
    return_tensors = utils.read_pb_return_tensors(graph, pb_file, return_elements)
  File "C:\dl-project\tensorflow-yolov3-master\core\utils.py", line 128, in read_pb_return_tensors
    return_elements=return_elements)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'LeakyRelu' in binary running on DESKTOP-G7BNMDL. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by YunYang1994** [comment]
check if your tensorflow version is 1.11.0

**Comment by ClayZhang0403** [comment]
> check if your tensorflow version is 1.11.0

i check it ，its true， is 1.11.0

**Comment by ClayZhang0403** [comment]
> check if your tensorflow version is 1.11.0

how  to solve this problem
