### ISSUE TITLE
File "convert_weight.py", line 66, in <module>     raise RuntimeError

### ISSUE THREAD

**Issue by CNUyue** [YunYang1994/tensorflow-yolov3#166]
BatchNorm/moving_variance
['yolov3/yolo-v3/Conv_6/weights', TensorShape([Dimension(1), Dimension(1), Dimension(1024), Dimension(255)])]
['conv_lbbox/weight', TensorShape([Dimension(1), Dimension(1), Dimension(1024), Dimension(75)])]
Traceback (most recent call last):
  File "convert_weight.py", line 66, in <module>
    raise RuntimeError
RuntimeError
有人遇到这个问题吗，求助

**Comment by change113** [comment]
这个是你训练完自己的数据以后，在运行convert_weight.py会报这个错？还是直接运行就报这个错了？

**Comment by CNUyue** [comment]
我就是直接训练VOC 数据直接报这个错，刚入门，请大佬帮忙 @change113 ，谢谢了

**Comment by change113** [comment]
按照作者的步骤走，不会有这个错的吧。重新下载项目，然后再次来过。试试......

**Comment by gulingfengze** [comment]
@CNUyue [you may try this](https://github.com/YunYang1994/tensorflow-yolov3/issues/191#issuecomment-502326770)

**Comment by wuranran** [comment]
我是训练完自己的数据以后，出现这个问题，请问如何让解决

**Comment by hexin6688** [comment]
> 
> 
> 我是训练完自己的数据以后，出现这个问题

> 
> 
> 我是训练完自己的数据以后，出现这个问题，请问如何让解决

请问怎么解决的呢？
