### ISSUE TITLE
Out of bound error

### ISSUE THREAD

**Issue by abeyang00** [YunYang1994/tensorflow-yolov3#175]
![Screenshot from 2019-05-29 13-08-16](https://user-images.githubusercontent.com/36392866/58528753-dd940b80-8212-11e9-986f-2fe7b44b205f.png)

This error occurs while training. Is this error with train.txt file?
If so, how can i print out the image path that is being fed?

**Comment by YunYang1994** [comment]
xmax < w and ymax < h

**Comment by greenrachel** [comment]
train loss: 736.09:  15%|████████████████████▎                                                                                                                | 1375/9029 [06:02<32:22,  3.94it/s][64 32 16]
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train.py", line 144, in train
    for train_data in pbar:
  File "/home/mousumi/anaconda3/envs/Tensorflow/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/mousumi/PycharmProjects/tensorflow-yolov3-master/core/dataset.py", line 90, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "/home/mousumi/PycharmProjects/tensorflow-yolov3-master/core/dataset.py", line 235, in preprocess_true_boxes
    label[i][yind, xind, iou_mask, :] = 0.0
IndexError: index 64 is out of bounds for axis 1 with size 64

After training for sometime, I got this error. why? and I am also confused about the anchor size. I used k-means algorithm to find out clusters for my dataset using your code but i am not sure it will work or not. The input image size is 512 and I am using VEDAI dataset for single class problem. I am interested to know that when I get clusters using k-means algorithm, they are actually normalized clusters with the scale of my dataset. So when I put the clusters in baseline_anchors.txt , should I use the normalized clusters or I need to multiply it with the scale of my input image.

**Comment by wenredo** [comment]
I guess it happens when the bboxes coordinates are parsed from the '_train.txt' file, the values of those coordinates must be in between some given values, but it would be great to get to know those values

**Comment by Bennett-Yang** [comment]
> xmax < w and ymax < h

I've already made sure that my xmax, xmin, ymax, ymin are in this range, but it still throw this error. I have to minus 1 manually. LOL

**Comment by MuhammadAsadJaved** [comment]
> > xmax < w and ymax < h
> 
> I've already made sure that my xmax, xmin, ymax, ymin are in this range, but it still throw this error. I have to minus 1 manually. LOL

Does this method work for you? I have similar problem , sometimes it throw error after two iterations , sometimes after 7 , and so on.

**Comment by Bennett-Yang** [comment]
> > > xmax < w and ymax < h
> > 
> > 
> > I've already made sure that my xmax, xmin, ymax, ymin are in this range, but it still throw this error. I have to minus 1 manually. LOL
> 
> Does this method work for you? I have similar problem , sometimes it throw error after two iterations , sometimes after 7 , and so on.

yes, it works for me.

**Comment by MuhammadAsadJaved** [comment]
> > > > xmax < w and ymax < h
> > > 
> > > 
> > > I've already made sure that my xmax, xmin, ymax, ymin are in this range, but it still throw this error. I have to minus 1 manually. LOL
> > 
> > 
> > Does this method work for you? I have similar problem , sometimes it throw error after two iterations , sometimes after 7 , and so on.
> 
> yes, it works for me.

Hi,   -1 from w or from h? or from both?   Can you share the script please
