### ISSUE TITLE
Pointless training results after yolov3 transfer learning with reduced coco2017 dataset 

### ISSUE THREAD

**Issue by Bienqq** [YunYang1994/tensorflow-yolov3#202]
Hello,

I was trying to perform yolov3 transfer learning, I started from train from COCO weights as described in README. In my coco2017 dataset I have only vehicles - 5 classes. In orginal model there are 80 classes. I used scripts from this repository to perform training and model export with following configuration:

**config.py**
```python
from easydict import EasyDict as edict


__C                             = edict()
# Consumers can get config by: from config import cfg

cfg                             = __C

# YOLO options
__C.YOLO                        = edict()

# Set the class name
__C.YOLO.CLASSES                = "./data/classes/my_classes.names"
__C.YOLO.ANCHORS                = "./data/anchors/coco_anchors.txt"
__C.YOLO.MOVING_AVE_DECAY       = 0.9995
__C.YOLO.STRIDES                = [8, 16, 32]
__C.YOLO.ANCHOR_PER_SCALE       = 3
__C.YOLO.IOU_LOSS_THRESH        = 0.5
__C.YOLO.UPSAMPLE_METHOD        = "resize"
__C.YOLO.ORIGINAL_WEIGHT        = "./checkpoint/my_best_checkpoint.ckpt"
__C.YOLO.DEMO_WEIGHT            = "./checkpoint/my_output.ckpt"

# Train options
__C.TRAIN                       = edict()

__C.TRAIN.ANNOT_PATH            = "./data/dataset/train_labels.txt"
__C.TRAIN.BATCH_SIZE            = 6
__C.TRAIN.INPUT_SIZE            = [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
__C.TRAIN.DATA_AUG              = True
__C.TRAIN.LEARN_RATE_INIT       = 1e-4
__C.TRAIN.LEARN_RATE_END        = 1e-6
__C.TRAIN.WARMUP_EPOCHS         = 2
__C.TRAIN.FISRT_STAGE_EPOCHS    = 20
__C.TRAIN.SECOND_STAGE_EPOCHS   = 30
__C.TRAIN.INITIAL_WEIGHT        = "./checkpoint/yolov3_coco_demo.ckpt"



# TEST options
__C.TEST                        = edict()

__C.TEST.ANNOT_PATH             = "./data/dataset/test_labels.txt" 
__C.TEST.BATCH_SIZE             = 2
__C.TEST.INPUT_SIZE             = 544
__C.TEST.DATA_AUG               = False
__C.TEST.WRITE_IMAGE            = True
__C.TEST.WRITE_IMAGE_PATH       = "./data/detection/"
__C.TEST.WRITE_IMAGE_SHOW_LABEL = False
__C.TEST.WEIGHT_FILE            = "./checkpoint/yolov3_test_loss=9.2099.ckpt-5"
__C.TEST.SHOW_LABEL             = False
__C.TEST.SCORE_THRESHOLD        = 0.3
__C.TEST.IOU_THRESHOLD          = 0.45

```
**my_classes.names**

```
car
truck
motorcycle
bicycle
bus
```

Training, convert_weights, and export freeze_graph was successful and I received 
my_yolov3.pb file which next I used in my video detector. 

But the detection results are really bad, they are definitely worse than using initial pretrained model... The detector can not find any objects.

Is it possible that such poor results are caused by a reduction in the number of classes from 80 to 5 ? Needs some changes in configuration ? Or any ideas what went wrong?

**Comment by shoutOutYangJie** [comment]
in the training process,  have the test loss ever been Nan?

**Comment by Bienqq** [comment]
No, the training itself was without problems.I released the whole process again and the results are quite good, it's possible that earlier I made some mistake.


1. After completing the training, I received 50 files with checkpoints, generated after each epoch. Which one is the best one? This file where total_loss is the smallest?

![image](https://user-images.githubusercontent.com/35897213/60047086-22ec1180-96c9-11e9-97c9-b3efad83ff88.png)

**Comment by CNUyue** [comment]
I use my trained model to generate .pb files(use convert_weights).The following questions occur, do you know what is going on?Thanks

Traceback (most recent call last):
  File "/home/lmy/Downloads/tensorflow-yolov3-master-kitti-dense/convert_weight.py", line 55, in <module>
    raise RuntimeError
RuntimeError

**Comment by 16534165** [comment]
> I use my trained model to generate .pb files(use convert_weights).The following questions occur, do you know what is going on?Thanks
> 
> Traceback (most recent call last):
> File "/home/lmy/Downloads/tensorflow-yolov3-master-kitti-dense/convert_weight.py", line 55, in
> raise RuntimeError
> RuntimeError

same,how to fix it
