### ISSUE TITLE
plot problem

### ISSUE THREAD

**Issue by vcvishal** [YunYang1994/tensorflow-yolov3#215]
when I ran python main.py -na 
then i encountered this 
Traceback (most recent call last):
  File "main.py", line 737, in <module>
    true_p_bar
  File "main.py", line 183, in draw_plot_func
    sorted_keys, sorted_values = zip(*sorted_dic_by_value)
ValueError: not enough values to unpack (expected 2, got 0)

please help 
thank you

**Comment by btsken** [comment]
i got the same problem

**Comment by a821836620** [comment]
I got the same problem,I found a reason. You should run evaluate.py before run main.py .If you run A, check if the output is predicted

**Comment by wuranran** [comment]
请问解决了吗

**Comment by wuranran** [comment]
> when I ran python main.py -na
> then i encountered this
> Traceback (most recent call last):
> File "main.py", line 737, in 
> true_p_bar
> File "main.py", line 183, in draw_plot_func
> sorted_keys, sorted_values = zip(*sorted_dic_by_value)
> ValueError: not enough values to unpack (expected 2, got 0)
> please help
> thank you
请问您解决了吗
