### ISSUE TITLE
IndexError: index 68 is out of bounds for axis 1 with size 60

### ISSUE THREAD

**Issue by Bienqq** [YunYang1994/tensorflow-yolov3#223]
Hello,

While training on my own dataset, I encountered the following problem. On other data sets like COCO this problem does not occur. 

Can anyone tell me what the cause is and how can it be solved?

Thanks in advance

```log
  File "/home/tomekb/yolov3_another/train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "/home/tomekb/yolov3_another/train.py", line 144, in train
    for train_data in pbar:
  File "/home/tomekb/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1017, in __iter__
    for obj in iterable:
  File "/home/tomekb/yolov3_another/core/dataset.py", line 82, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "/home/tomekb/yolov3_another/core/dataset.py", line 244, in preprocess_true_boxes
    label[best_detect][yind, xind, best_anchor, :] = 0
IndexError: index 68 is out of bounds for axis 1 with size 60

```

**Comment by YunYang1994** [comment]
bbox : [xmin, ymin, xmax, ymax]

make sure that `xmin > 0 , xmax < width, ymin > 0, ymax < height `

**Comment by HtutLynn** [comment]
This is what I did to the preprocess_true_boxes func in dataset.py :
xind,yind = abs(xind),abs(yind)
if yind >= label[best_detect].shape[1]:
   yind = label[best_detect].shape[1] - 1
if xind >= label[best_detect].shape[0]:
   xind = label[best_detect].shape[0] -1

This solved the problem and I think it would work fine too.

**Comment by Frank-qlu** [comment]
更换数据集后，.names换成一类，训练时候dataset.py报错，请问什么原因，怎么解决？
Instructions for updating:
Use standard file APIs to check for files with this prefix.
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train.py", line 144, in train
    for train_data in pbar:
  File "F:\Lee\tensorflow_for_YOLOv3\venv\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "F:\Lee\tensorflow-yolov3-master\core\dataset.py", line 82, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "F:\Lee\tensorflow-yolov3-master\core\dataset.py", line 244, in preprocess_true_boxes
    label[best_detect][yind, xind, best_anchor, :] = 0
IndexError: index 52 is out of bounds for axis 1 with size 52
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]

**Comment by EEeEhh** [comment]
> bbox : [xmin, ymin, xmax, ymax]
> 
> make sure that `xmin > 0 , xmax < width, ymin > 0, ymax < height `

只要注意up bound就可以了吧，即xmin >= 0, ymin >= 0, xmax <width, ymax < height.
