### ISSUE TITLE
How to implement a grayscaled image dataset?

### ISSUE THREAD

**Issue by ltorlay** [YunYang1994/tensorflow-yolov3#230]
I want to implement a grayscale dataset with this great network! I plan to use something along the lines of cv2.cvtColor(_image_ , cv2.COLOR_BGR2GRAY).astype(np.float32) However, I don't know what else to edit in dataset.py and subsequent files to accommodate one channel? Please let me know if anyone can confirm a way of doing this. 

Thanks, 
Lucas

**Comment by ltorlay** [comment]
**Here is the current traceback error I am experiencing:**

```
=> Now it starts to train YOLOV3 from scratch ...
  0%|                                                                             | 0/79 [00:00<?, ?it/s]OpenCV Error: Assertion failed (depth == CV_8U || depth == CV_16U || depth == CV_32F) in cvtColor, file /home/travis/miniconda/conda-bld/conda_1486587069159/work/opencv-3.1.0/modules/imgproc/src/color.cpp, line 7935
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train.py", line 144, in train
    for train_data in pbar:
  File "/home/lucas/anaconda3/envs/tensorflow_gpu/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "/home/lucas/Documents/Tensorflow/workspace/tensorflow-yolov3/core/dataset.py", line 84, in __next__
    image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY).astype(np.float32)  ######### edit
cv2.error: /home/travis/miniconda/conda-bld/conda_1486587069159/work/opencv-3.1.0/modules/imgproc/src/color.cpp:7935: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cvtColor
```

**Lines of edited code in dataset.py:**
```
                    annotation = self.annotations[index]
                    image, bboxes = self.parse_annotation(annotation)
                    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes =       self.preprocess_true_boxes(bboxes)

                    image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY).astype(np.float32)  ######### edit
                    batch_image[num, :, :, :] = image
                    batch_label_sbbox[num, :, :, :, :] = label_sbbox

```
Please offer any insight you may have! I'll be sure to credit you along with this repository for your collaboration.

Thanks again,
Lucas

**Comment by ltorlay** [comment]
For future reference, how I solved this issue was adding 
image = image.astype(np.float32) to the line before cvtColor and adding
image = np.expand_dims(image, axis=-1) to the line after cvtColor

**Comment by anmol4210** [comment]
it should be RGB2GRAY and not BGR2GRAY
