### ISSUE TITLE
Training issue shows out of range

### ISSUE THREAD

**Issue by yhemily** [YunYang1994/tensorflow-yolov3#24]
Hi,

I run the train.py in the latest package to train the Yolov3 , but it shows
    loss_class += result[3]
    IndexError: tuple index out of range

In quick_train.py, I can run the process success and show the result 1.0 and 0.0.

Could you help to check the issue in train.py?
Thanks a lot for your help! =)

**Comment by Matthew43** [comment]
I also met this problem, and I found the problem because the function 
`def loss_layer(self, feature_map_i, y_true, anchors, ignore_thresh, max_box_per_image)`
ended  prematurely, so I commented this in line 338 
` # return object_mask, intersect_area, iou_scores`

then, it works.

**Comment by huyazhou-2018** [comment]
我注释了这一行，训练过程中loss都是nan，这正常吗？

**Comment by qiaomai89** [comment]
@Matthew43  Hi, thanks for your anwser!
But I have tried the one, there is error:
InvalidArgumentError (see above for traceback): ValueError: could not broadcast input array from shape (10,4) into shape (8,4)
         [[Node: yolov3/PyFunc_1 = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext:2)]]

do you have any idea about this one?

And also, it seems that if commented this in line 338, the results in training process will be NAN

**Comment by qiaomai89** [comment]
@Matthew43   this is the whole information about the error:

=> loading  yolov3/darknet-53/Conv_49/weights:0
=> loading  yolov3/darknet-53/Conv_49/BatchNorm/gamma:0
=> loading  yolov3/darknet-53/Conv_50/weights:0
=> loading  yolov3/darknet-53/Conv_50/BatchNorm/gamma:0
=> loading  yolov3/darknet-53/Conv_51/weights:0
=> loading  yolov3/darknet-53/Conv_51/BatchNorm/gamma:0
=> EPOCH:         0     total_loss:    nan      loss_xy: 0.0049 loss_wh:    nan loss_conf: 0.7943       loss_class: 0.0052      rec_50: 0.0000  rec_70: 0.0000  avg_iou: 0.0000
=> EPOCH:         1     total_loss:    nan      loss_xy:    nan loss_wh:    nan loss_conf:    nan       loss_class:    nan      rec_50: 0.0000  rec_70: 0.0000  avg_iou:    nan
=> EPOCH:         2     total_loss:    nan      loss_xy:    nan loss_wh:    nan loss_conf:    nan       loss_class:    nan      rec_50: 0.0000  rec_70: 0.0000  avg_iou:    nan
=> EPOCH:         3     total_loss:    nan      loss_xy:    nan loss_wh:    nan loss_conf:    nan       loss_class:    nan      rec_50: 0.0000  rec_70: 0.0000  avg_iou:    nan
=> EPOCH:         4     total_loss:    nan      loss_xy:    nan loss_wh:    nan loss_conf:    nan       loss_class:    nan      rec_50: 0.0000  rec_70: 0.0000  avg_iou:    nan
2019-01-15 22:43:22.964638: W tensorflow/core/framework/op_kernel.cc:1190] Invalid argument: ValueError: could not broadcast input array from shape (10,4) into shape (8,4)
Traceback (most recent call last):
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: could not broadcast input array from shape (10,4) into shape (8,4)
         [[Node: yolov3/PyFunc_1 = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext:2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 64, in <module>
    run_items = sess.run([train_op, write_op] + loss, feed_dict={is_training:True})
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: could not broadcast input array from shape (10,4) into shape (8,4)
         [[Node: yolov3/PyFunc_1 = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext:2)]]

Caused by op 'yolov3/PyFunc_1', defined at:
  File "train.py", line 35, in <module>
    loss = model.compute_loss(y_pred, y_true)
  File "/DALAB/DATA1/suhuiqiao/new-tensorflow-yolov3-master/core/yolov3.py", line 256, in compute_loss
    result = self.loss_layer(y_pred[i], y_true[i], _ANCHORS[i], ignore_thresh, max_box_per_image)
  File "/DALAB/DATA1/suhuiqiao/new-tensorflow-yolov3-master/core/yolov3.py", line 356, in loss_layer
    true_boxes = tf.py_func(pick_out_gt_box, [y_true], [tf.float32] )[0]
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 317, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 225, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_script_ops.py", line 93, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/suhuiqiao/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): ValueError: could not broadcast input array from shape (10,4) into shape (8,4)
         [[Node: yolov3/PyFunc_1 = PyFunc[Tin=[DT_FLOAT], Tout=[DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorGetNext:2)]]

**Comment by yuanCnD** [comment]
loss_wh 的计算方式有问题，第一次计算为nan，后面加到total_loss之后使之也为nan。

**Comment by YunYang1994** [comment]
```
=> EPOCH:     19986 	total_loss: 0.0041 	loss_xy: 0.0010 	loss_wh: 0.0023 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19987 	total_loss: 0.0022 	loss_xy: 0.0006 	loss_wh: 0.0009 	loss_conf: 0.0007 	loss_class: 0.0000
=> EPOCH:     19988 	total_loss: 0.0035 	loss_xy: 0.0005 	loss_wh: 0.0012 	loss_conf: 0.0018 	loss_class: 0.0000
=> EPOCH:     19989 	total_loss: 0.0024 	loss_xy: 0.0009 	loss_wh: 0.0008 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19990 	total_loss: 0.0060 	loss_xy: 0.0034 	loss_wh: 0.0018 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19991 	total_loss: 0.0056 	loss_xy: 0.0032 	loss_wh: 0.0017 	loss_conf: 0.0007 	loss_class: 0.0000
=> EPOCH:     19992 	total_loss: 0.0045 	loss_xy: 0.0024 	loss_wh: 0.0014 	loss_conf: 0.0007 	loss_class: 0.0000
=> EPOCH:     19993 	total_loss: 0.0026 	loss_xy: 0.0010 	loss_wh: 0.0009 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19994 	total_loss: 0.0048 	loss_xy: 0.0017 	loss_wh: 0.0023 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19995 	total_loss: 0.0047 	loss_xy: 0.0032 	loss_wh: 0.0008 	loss_conf: 0.0007 	loss_class: 0.0000
=> EPOCH:     19996 	total_loss: 0.0027 	loss_xy: 0.0011 	loss_wh: 0.0008 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19997 	total_loss: 0.0023 	loss_xy: 0.0010 	loss_wh: 0.0005 	loss_conf: 0.0008 	loss_class: 0.0000
=> EPOCH:     19998 	total_loss: 0.0027 	loss_xy: 0.0010 	loss_wh: 0.0010 	loss_conf: 0.0007 	loss_class: 0.0000
```
