### ISSUE TITLE
IndexError:index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by PoomPoomPa** [YunYang1994/tensorflow-yolov3#278]
when i ran train.py,i met the problem about index error:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/tensorflow-yolov3-master/train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "G:/tensorflow-yolov3-master/train.py", line 144, in train
    for train_data in pbar:
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "G:\tensorflow-yolov3-master\core\dataset.py", line 81, in __next__
    image, bboxes = self.parse_annotation(annotation)
  File "G:\tensorflow-yolov3-master\core\dataset.py", line 167, in parse_annotation
    image, bboxes = self.random_translate(np.copy(image), np.copy(bboxes))
  File "G:\tensorflow-yolov3-master\core\dataset.py", line 139, in random_translate
    max_u_trans = max_bbox[1]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by zhangscth** [comment]
i have met the same problem!   @YunYang1994

**Comment by Frank-qlu** [comment]
更换数据集后，.names换成一类，训练时候dataset.py报错，请问什么原因，怎么解决？
Instructions for updating:
Use standard file APIs to check for files with this prefix.
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train.py", line 144, in train
    for train_data in pbar:
  File "F:\Lee\tensorflow_for_YOLOv3\venv\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "F:\Lee\tensorflow-yolov3-master\core\dataset.py", line 82, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "F:\Lee\tensorflow-yolov3-master\core\dataset.py", line 244, in preprocess_true_boxes
    label[best_detect][yind, xind, best_anchor, :] = 0
IndexError: index 52 is out of bounds for axis 1 with size 52
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]

**Comment by ellietot** [comment]
check your dataset.txt, ensure that it has the format as follow(as the author mentioned):
xxx/xxx.jpg 48,240,195,371,11 8,12,352,498,14
i.e.filename bbox1,id bbox2,id ...
pay attention to the cooma and space.
Good Luck!

**Comment by sqWa** [comment]
> check your dataset.txt, ensure that it has the format as follow(as the author mentioned):
> xxx/xxx.jpg 48,240,195,371,11 8,12,352,498,14
> i.e.filename bbox1,id bbox2,id ...
> pay attention to the cooma and space.
> Good Luck!

谢谢！确实是因为在标注信息之间不是逗号，而是用的空格，导致了这个错误。已解决。
格式要严格按照作者的标准来进行，空格和逗号需要注意。
