### ISSUE TITLE
使用video_demo.py出现如下问题，怎么解决？

### ISSUE THREAD

**Issue by JimmyLee99** [YunYang1994/tensorflow-yolov3#298]
Traceback (most recent call last):
  File "video_demo.py", line 55, in <module>
    image = utils.draw_bbox(frame, bboxes)
  File "/home/robot6/桌面/tensorflow-yolov3/core/utils.py", line 83, in draw_bbox
    bbox_color = colors[class_ind]
IndexError: list index out of range

**Comment by JimmyLee99** [comment]
重新把包装了一遍有可以用了，可能是训练自己的数据集的时候该来某些参数导致的

**Comment by Dontla** [comment]
Have you solved this problem?

**Comment by JimmyLee99** [comment]
> Have you solved this probl

> Have you solved this problem?

clean all, and then restall it
