### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: ./checkpoint/yolov3_test_loss=9.2099.ckpt-5

### ISSUE THREAD

**Issue by JimmyLee99** [YunYang1994/tensorflow-yolov3#299]
按照楼主的方法训练了voc，之后运行了evaluate.py出现如下问题，应该如何解决呢？
Traceback (most recent call last):
  File "evaluate.py", line 162, in <module>
    if __name__ == '__main__': YoloTest().evaluate()
  File "evaluate.py", line 51, in __init__
    self.saver.restore(self.sess, self.weight_file)
  File "/home/robot6/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1278, in restore
    compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: ./checkpoint/yolov3_test_loss=9.2099.ckpt-5

**Comment by YunYang1994** [comment]
检查下tensorflow版本

**Comment by JimmyLee99** [comment]
用的tensorflow1.14-cpu版本，还是得要安装tensorflow1.11-gpu才行？

**Comment by YunYang1994** [comment]
tensorflow1.11-cpu 应该也行

**Comment by jvxiao** [comment]
将 ./checkpoint/yolov3_test_loss=9.2099.ckpt-5 改成你自己checkpoint目录下的文件名，而且不要加上.data-0000-of-0000x这个后缀。比如我的文件是：yolov3_test_loss=40.0239.ckpt-2.data-00000-of-00001，那么就写yolov3_test_loss=40.0239.ckpt-2

**Comment by navy63** [comment]
RTX 2080TI 11G显存，为什么训练了20epoch会提示显存不足
 [[node define_loss/prob_loss/add_1 (defined at E:\Infrared_Deeplearning\YOLOV3\tensorflow-yolov3-master\core\yolov3.py:254) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by navy63** [comment]
修改这个路径名字就可以了。他这里写死了
__C.TEST.WEIGHT_FILE            = "./checkpoint/yolov3_test_loss=9.9054.ckpt-50"

**Comment by Theriyadh** [comment]
You should change the file  in core/config.py to your own weight file. You can find your write file in checkpoint folder.

**Comment by Tom127** [comment]
> RTX 2080TI 11G显存，为什么训练了20epoch会提示显存不足
> [[node define_loss/prob_loss/add_1 (defined at E:\Infrared_Deeplearning\YOLOV3\tensorflow-yolov3-master\core\yolov3.py:254) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

你好，我也遇到了这个问题，请问你是怎么解决的？

**Comment by HaruStone** [comment]
> > RTX 2080TI 11G显存，为什么训练了20epoch会提示显存不足
> > [[node define_loss/prob_loss/add_1 (defined at E:\Infrared_Deeplearning\YOLOV3\tensorflow-yolov3-master\core\yolov3.py:254) ]]
> > Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 
> 你好，我也遇到了这个问题，请问你是怎么解决的？

更改 core/config.py 里的 __C.TRAIN.BATCH_SIZE   = 6，我把改成4就行了
