### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by chaoyangfan** [YunYang1994/tensorflow-yolov3#304]
你好，我按照你的步骤运行时。在运行python convert_weight.py时，报错如下，请问该怎么解决呢？谢谢
2019-09-02 11:45:22.657142: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-02 11:45:24.462819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:84:00.0
totalMemory: 7.92GiB freeMemory: 7.81GiB
2019-09-02 11:45:24.737067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:88:00.0
totalMemory: 7.92GiB freeMemory: 7.81GiB
2019-09-02 11:45:24.738091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0, 1
Traceback (most recent call last):
  File "convert_weight.py", line 31, in <module>
    with tf.Session() as sess:
  File "/home/wutt/anaconda3/envs/fancy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1511, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/wutt/anaconda3/envs/fancy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 634, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

**Comment by wangshiqq2888** [comment]
刚从darknet转过来，之前用的CUDA10.1。我运行convert_weight.py也会报错


ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.

**Comment by TsingWei** [comment]
用cuda9.0
