### ISSUE TITLE
更换数据之后的错ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by limingyue123** [YunYang1994/tensorflow-yolov3#315]
bboxes = np.array([list(map(int, box.split(','))) for box in line[1:]])
ValueError: invalid literal for int() with base 10: ''
我换了一个数据集之后在运行就会出错，如上所示。
小白，请求帮助@YunYang1994

**Comment by limingyue123** [comment]
File "train.py", line 208, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train.py", line 148, in train
    for train_data in pbar:
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/workspace/tensorflow-yolov3-master-SUNRGBD/core/dataset.py", line 71, in __next__
    image, bboxes = self.parse_annotation(annotation)
  File "/workspace/tensorflow-yolov3-master-SUNRGBD/core/dataset.py", line 151, in parse_annotation
    bboxes = np.array([list(map(int, box.split(','))) for box in line[1:]])
  File "/workspace/tensorflow-yolov3-master-SUNRGBD/core/dataset.py", line 151, in <listcomp>
    bboxes = np.array([list(map(int, box.split(','))) for box in line[1:]])
ValueError: invalid literal for int() with base 10: ''

**Comment by Frank-qlu** [comment]
请问解决了，我在模型评估时候也遇到同样问题
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "evaluate.py", line 162, in <module>
    if __name__ == '__main__': YoloTest().evaluate()
  File "evaluate.py", line 93, in evaluate
    bbox_data_gt = np.array([list(map(int, box.split(','))) for box in annotation[1:]])
  File "evaluate.py", line 93, in <listcomp>
    bbox_data_gt = np.array([list(map(int, box.split(','))) for box in annotation[1:]])
ValueError: invalid literal for int() with base 10: '0.529851'

**Comment by DLwyp** [comment]
> File "train.py", line 208, in
> if **name** == '**main**': YoloTrain().train()
> File "train.py", line 148, in train
> for train_data in pbar:
> File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 930, in **iter**
> for obj in iterable:
> File "/workspace/tensorflow-yolov3-master-SUNRGBD/core/dataset.py", line 71, in **next**
> image, bboxes = self.parse_annotation(annotation)
> File "/workspace/tensorflow-yolov3-master-SUNRGBD/core/dataset.py", line 151, in parse_annotation
> bboxes = np.array([list(map(int, box.split(','))) for box in line[1:]])
> File "/workspace/tensorflow-yolov3-master-SUNRGBD/core/dataset.py", line 151, in
> bboxes = np.array([list(map(int, box.split(','))) for box in line[1:]])
> ValueError: invalid literal for int() with base 10: ''

把bboxes = np.array([list(map(int, box.split(','))) for box in line[1:]])中的int改成float就行了
