### ISSUE TITLE
File ".../tensorflow-yolov3/core/utils.py", line 379. ndexError: index 58 is out of bounds for axis 3 with size 25

### ISSUE THREAD

**Issue by jiaweichen168** [YunYang1994/tensorflow-yolov3#32]
File ".../tensorflow-yolov3/core/utils.py", line 379, in preprocess_true_boxes
    y_true[l][i, j, k, 5+c] = 1

IndexError: index 58 is out of bounds for axis 3 with size 25

**Comment by YunYang1994** [comment]
hello, codes has beed updated now! I think your issues has been solved

**Comment by SettleSun** [comment]
Traceback (most recent call last):
  File "quick_test.py", line 33, in <module>
    boxes, scores, labels = utils.cpu_nms(boxes, scores, num_classes, score_thresh=0.3, iou_thresh=0.5)
  File "I:\PythonWorkspace\cetc_image_2_class_001\core\utils.py", line 122, in cpu_nms
    filter_boxes = boxes[indices]
IndexError: index 22673 is out of bounds for axis 0 with size 10647

**Comment by prasantth96** [comment]
Traceback (most recent call last):
  File "quick_test.py", line 33, in <module>
    boxes, scores, labels = utils.cpu_nms(boxes, scores, num_classes, score_thresh=0.3, iou_thresh=0.5)
  File "/home/uniten/Documents/MyPythonFiles/tensorflow-yolov3-yunyang1994/core/utils.py", line 122, in cpu_nms
    filter_boxes = boxes[indices]


please help me to solve this issue
