### ISSUE TITLE
could not broadcast input array from shape (3,2) into shape (9,2)

### ISSUE THREAD

**Issue by icoicqico** [YunYang1994/tensorflow-yolov3#332]
0%|          | 0/406 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\tensorflow-yolov3-master\train.py", line 173, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "E:\tensorflow-yolov3-master\train.py", line 133, in train
    for train_data in pbar:
  File "C:\Users\captain\AppData\Local\Programs\Python\Python36\lib\site-packages\tqdm\_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "E:\tensorflow-yolov3-master\core\dataset.py", line 82, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "E:\tensorflow-yolov3-master\core\dataset.py", line 218, in preprocess_true_boxes
    anchors_xywh[:, 2:4] = self.anchors[i]
ValueError: could not broadcast input array from shape (3,2) into shape (9,2)

**Comment by icoicqico** [comment]
(anchors_xywh[:, 2:4])
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

(self.anchors[i])
[[1.25  1.625]
 [2.    3.75 ]
 [4.125 2.875]]

**Comment by icoicqico** [comment]
Problem fixed, just some settings problem
