### ISSUE TITLE
IndexError: index 52 is out of bounds for axis 1 with size 52

### ISSUE THREAD

**Issue by Frank-qlu** [YunYang1994/tensorflow-yolov3#341]
更换数据集后，.names换成一类，训练时候dataset.py 244行报错，请问什么原因，怎么解决？
Instructions for updating:
Use standard file APIs to check for files with this prefix.
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 184, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "train.py", line 144, in train
    for train_data in pbar:
  File "F:\Lee\tensorflow_for_YOLOv3\venv\lib\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "F:\Lee\tensorflow-yolov3-master\core\dataset.py", line 82, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "F:\Lee\tensorflow-yolov3-master\core\dataset.py", line 244, in preprocess_true_boxes
    label[best_detect][yind, xind, best_anchor, :] = 0
IndexError: index 52 is out of bounds for axis 1 with size 52
  0%|                                                                                           | 0/17 [00:00<?, ?it/s]

**Comment by Frank-qlu** [comment]
已解决

**Comment by liam181113** [comment]
请问训练自己数据集，检测效果怎么样啊？

**Comment by Frank-qlu** [comment]
> 请问训练自己数据集，检测效果怎么样啊？
正在训练

**Comment by Code-Fight** [comment]
@Frank-qlu 怎么解决的 我也有同样的问题

**Comment by farazBhatti** [comment]
Hi, i am also getting the same error.

`IndexError: index 76 is out of bounds for axis 1 with size 76
`.
I am using custom dataset with training.txt file in the following manner 

`./complete/imgs/CAR00718.jpg0.851124,0.291667,0.196629,0.125000,15`

**Comment by YunYang1994** [comment]
be sure that " 0<=xmax <= width and 0<=ymax<=height "

**Comment by EEeEhh** [comment]
> 已解决

大佬可以讲述一下怎么回事吗？

**Comment by fxcdl** [comment]
> 已解决

您好 请问您是怎么解决这个问题的？

**Comment by CNUyue** [comment]
您好，问一下您怎么解决的

**Comment by EEeEhh** [comment]
> 您好，问一下您怎么解决的

确实是因为数据集的label问题，你生成annotation文件的时候注意检查label的正确性就可以。
