### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '0.529851'

### ISSUE THREAD

**Issue by Frank-qlu** [YunYang1994/tensorflow-yolov3#342]
更换数据集，训练之后执行python evaluate.py出错，请问什么原因，怎么解决？
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "evaluate.py", line 162, in <module>
    if __name__ == '__main__': YoloTest().evaluate()
  File "evaluate.py", line 93, in evaluate
    bbox_data_gt = np.array([list(map(int, box.split(','))) for box in annotation[1:]])
  File "evaluate.py", line 93, in <listcomp>
    bbox_data_gt = np.array([list(map(int, box.split(','))) for box in annotation[1:]])
ValueError: invalid literal for int() with base 10: '0.529851'

**Comment by Frank-qlu** [comment]
已解决

**Comment by Kazusa853** [comment]
你好，请问你这个问题怎么解决的？
