### ISSUE TITLE
convert_weight.py 报错RuntimeError

### ISSUE THREAD

**Issue by cloudrivers** [YunYang1994/tensorflow-yolov3#466]
Hi，我自己训练了一个数据集，然后调用convert_weight.py的时候报下面的错误，请问是什么原因啊？
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-2ed498e8931e> in <module>()
     57 cur_weights_num = len(cur_weights_mess)
     58 if cur_weights_num != org_weights_num:
---> 59     raise RuntimeError
     60 
     61 print('=> Number of weights that will rename:\t%d' % cur_weights_num)

RuntimeError:

**Comment by natsume7** [comment]
https://github.com/YunYang1994/tensorflow-yolov3/issues/368

**Comment by hexin6688** [comment]
你好，我也出现了这个问题，然后我直接freze_graph.py生成了.pb文件之后，运行train.py又出现Traceback (most recent call last):
  File "G:/数据集/tensorflow-yolov3-master/image_demo.py", line 43, in <module>
    np.reshape(pred_lbbox, (-1, 5 + num_classes))], axis=0)
  File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 3549 into shape (6)
