### ISSUE TITLE
运行train.py，训练自己数据集，出现问题

### ISSUE THREAD

**Issue by wy-use** [YunYang1994/tensorflow-yolov3#467]
想问下 在运行 train.py 的时候 出现这样的问题 是什么原因呢？
54:21.558613: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
train loss: 53.78: 100%|████████████████████| 7889/7889 [07:29<00:00, 17.56it/s]
Traceback (most recent call last):
File "train.py", line 184, in 
if name == 'main': YoloTrain().train()
File "train.py", line 161, in train
for test_data in self.testset:
File "/home/administrator/m1/yolo/人脸数据集/tensorflow-yolov3-master/core/dataset.py", line 82, in next
label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
File "/home/administrator/m1/yolo/人脸数据集/tensorflow-yolov3-master/core/dataset.py", line 244, in preprocess_true_boxes
label[best_detect][yind, xind, best_anchor, :] = 0
IndexError: index 41 is out of bounds for axis 1 with size 40

请各位大佬指导一下

**Comment by fxcdl** [comment]
请问你解决了吗 我也遇到了这个问题

**Comment by jinyixin621** [comment]
要用0作为第一个类别的class

**Comment by CNUyue** [comment]
你好，我也遇到了相同的问题，您解决了吗@wy-use

**Comment by tuzhirun** [comment]
你好，你的数据集是怎么配置的？他给的训练自己的步骤不太明白，谢谢了

**Comment by nanshenwei** [comment]
加一个backgroup到class.names作为第0个class
