### ISSUE TITLE
训练测试

### ISSUE THREAD

**Issue by wl4135** [YunYang1994/tensorflow-yolov3#515]
我原先训练测试过一批数据，map在90%，但是什么参数也没改，数据也没变再训练一次map值就下降到50%了这是什么原因？我用的google colab训练的，因为之前把数据下载到了本地，今天重新上传到colab再训练就成这样了，大佬们这是什么原因？

**Comment by hexin6688** [comment]
attributeError:tensorflow has no attribute names 'Session',我在tensorflow-gpu-2.0.0，然后换成tensorflow-gpu-1.14.0还是不行。请问可以解答一些么？

**Comment by wl4135** [comment]
> attributeError:tensorflow has no attribute names 'Session',我在tensorflow-gpu-2.0.0，然后换成tensorflow-gpu-1.14.0还是不行。请问可以解答一些么？

你把之前的2.0版本卸载干净再装1.14版本，安装了先测试一下是不是安装成功。我使用的是1.13.1版本，在ubuntu18.04操作系统下操作的

**Comment by wl4135** [comment]
已解决，增加训练epochs数，至少得50个epochs吧，看你自己的数据了，数据太少训练太多容易过拟合，还有什么好方法大佬可以评论指点一下

**Comment by hexin6688** [comment]
Use standard file APIs to check for files with this prefix.
=> ./checkpoint/yolov3_coco_demo.ckpt does not exist !!!
=> Now it starts to train YOLOV3 from scratch ...
请问，我checkpoint里面有模型，为什么说不存在呢？

**Comment by hexin6688** [comment]
checkpoint里有demo.ckpt,data/demo.ckpt,index/demo.ckpt,meta三个文件

**Comment by wl4135** [comment]
> Use standard file APIs to check for files with this prefix.
> => ./checkpoint/yolov3_coco_demo.ckpt does not exist !!!
> => Now it starts to train YOLOV3 from scratch ...
> 请问，我checkpoint里面有模型，为什么说不存在呢？

一般你这样存在的文件运行不存在就是路径问题，问题不大，你好好查查你的路径

**Comment by hexin6688** [comment]
路径我没有改过，config.py里面的路径“./checkpoint/yolov3_coco_demo.ckpt”是没有问题的



---原始邮件---
发件人: "wanglei"<notifications@github.com&gt;
发送时间: 2020年4月18日(周六) 上午9:57
收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hexin6688"<790234486@qq.com&gt;;
主题: Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515)




  
Use standard file APIs to check for files with this prefix.
 =&gt; ./checkpoint/yolov3_coco_demo.ckpt does not exist !!!
 =&gt; Now it starts to train YOLOV3 from scratch ...
 请问，我checkpoint里面有模型，为什么说不存在呢？
  
一般你这样存在的文件运行不存在就是路径问题，问题不大，你好好查查你的路径

**Comment by wl4135** [comment]
> 路径我没有改过，config.py里面的路径“./checkpoint/yolov3_coco_demo.ckpt”是没有问题的
> […](#)
> ---原始邮件--- 发件人: "wanglei"<notifications@github.com&gt; 发送时间: 2020年4月18日(周六) 上午9:57 收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"hexin6688"<790234486@qq.com&gt;; 主题: Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515) Use standard file APIs to check for files with this prefix. =&gt; ./checkpoint/yolov3_coco_demo.ckpt does not exist !!! =&gt; Now it starts to train YOLOV3 from scratch ... 请问，我checkpoint里面有模型，为什么说不存在呢？ 一般你这样存在的文件运行不存在就是路径问题，问题不大，你好好查查你的路径 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

那就不知道了，因为我之前用过tf的object_detection API做过目标检测，也是路径问题，因为文件存在。你再检查检查

**Comment by hexin6688** [comment]
请问你有遇到过这种问题么，用自己训练的model做运行imag_demo.py的时候
Traceback (most recent call last):
File "G:/数据集/tensorflow-yolov3-master/image_demo.py", line 43, in&nbsp;
np.reshape(pred_lbbox, (-1, 5 + num_classes))], axis=0)
File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 292, in reshape
return _wrapfunc(a, 'reshape', newshape, order=order)
File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 3549 into shape (6)


---原始邮件---
发件人: "wanglei"<notifications@github.com&gt;
发送时间: 2020年4月19日(周日) 上午10:10
收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"hexin6688"<790234486@qq.com&gt;;
主题: Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515)




  
路径我没有改过，config.py里面的路径“./checkpoint/yolov3_coco_demo.ckpt”是没有问题的
 …
 ---原始邮件--- 发件人: "wanglei"<notifications@github.com&gt; 发送时间: 2020年4月18日(周六) 上午9:57 收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"hexin6688"<790234486@qq.com&gt;; 主题: Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515) Use standard file APIs to check for files with this prefix. =&gt; ./checkpoint/yolov3_coco_demo.ckpt does not exist !!! =&gt; Now it starts to train YOLOV3 from scratch ... 请问，我checkpoint里面有模型，为什么说不存在呢？ 一般你这样存在的文件运行不存在就是路径问题，问题不大，你好好查查你的路径 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
那就不知道了，因为我之前用过tf的object_detection API做过目标检测，也是路径问题，因为文件存在。你再检查检查

**Comment by wl4135** [comment]
> 请问你有遇到过这种问题么，用自己训练的model做运行imag_demo.py的时候 Traceback (most recent call last): File "G:/数据集/tensorflow-yolov3-master/image_demo.py", line 43, in&nbsp; np.reshape(pred_lbbox, (-1, 5 + num_classes))], axis=0) File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 292, in reshape return _wrapfunc(a, 'reshape', newshape, order=order) File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc return getattr(obj, method)(*args, **kwds) ValueError: cannot reshape array of size 3549 into shape (6)
> […](#)
> ---原始邮件--- 发件人: "wanglei"<notifications@github.com&gt; 发送时间: 2020年4月19日(周日) 上午10:10 收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"hexin6688"<790234486@qq.com&gt;; 主题: Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515) 路径我没有改过，config.py里面的路径“./checkpoint/yolov3_coco_demo.ckpt”是没有问题的 … ---原始邮件--- 发件人: "wanglei"<notifications@github.com&gt; 发送时间: 2020年4月18日(周六) 上午9:57 收件人: "YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"hexin6688"<790234486@qq.com&gt;; 主题: Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515) Use standard file APIs to check for files with this prefix. =&gt; ./checkpoint/yolov3_coco_demo.ckpt does not exist !!! =&gt; Now it starts to train YOLOV3 from scratch ... 请问，我checkpoint里面有模型，为什么说不存在呢？ 一般你这样存在的文件运行不存在就是路径问题，问题不大，你好好查查你的路径 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 那就不知道了，因为我之前用过tf的object_detection API做过目标检测，也是路径问题，因为文件存在。你再检查检查 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

这个问题没有遇到过，image_demo目前检测使用正常

**Comment by zerozhoujie** [comment]
请问你有没有遇到训练loss=nan的问题？我第一阶段训练20次，第二阶段训练设置的2000，训练图片4200张，测试图片800张，但是在训练到24次的时候遇到test-loss=nan的问题，大佬求解

**Comment by zerozhoujie** [comment]
请问你有没有遇到训练loss = nan的问题？我第一阶段训练20次，第二阶段训练设置的2000，训练图片4200张，测试图片800张，但是在训练到24次的时候遇到测试-loss = nan的问题，大佬求解
![image](https://user-images.githubusercontent.com/40144255/79933030-6cd88c00-8481-11ea-8601-d10191260858.png)

**Comment by zerozhoujie** [comment]
请问你有没有遇到训练loss = nan的问题？我第一阶段训练20次，第二阶段训练设置的2000，训练图片4200张，测试图片800张，但是在训练到24次的时候遇到测试-loss = nan的问题，大佬求解
![image](https://user-images.githubusercontent.com/40144255/79933076-8679d380-8481-11ea-9db6-2a4300c3b9fe.png)

**Comment by wl4135** [comment]
> 请问你有没有遇到训练loss = nan的问题？我第一阶段训练20次，第二阶段训练设置的2000，训练图片4200张，测试图片800张，但是在训练到24次的时候遇到测试-loss = nan的问题，大佬求解
> ![image](https://user-images.githubusercontent.com/40144255/79933076-8679d380-8481-11ea-9db6-2a4300c3b9fe.png)

没出现过这种nan的情况啊

**Comment by yifeichenNJ** [comment]
> 我原先训练测试过一批数据，map在90%，但是什么参数也没改，数据也没变再训练一次map值就下降到50%了这是什么原因？我用的google colab训练的，因为之前把数据下载到了本地，今天重新上传到colab再训练就成这样了，大佬们这是什么原因？



> 我原先训练测试过一批数据，map在90%，但是什么参数也没改，数据也没变再训练一次map值就下降到50%了这是什么原因？我用的google colab训练的，因为之前把数据下载到了本地，今天重新上传到colab再训练就成这样了，大佬们这是什么原因？

你好，请问在用自己的数据集进行训练时，是不是不能使用作者给的预训练权重

**Comment by yifeichenNJ** [comment]
> 我原先训练测试过一批数据，map在90%，但是什么参数也没改，数据也没变再训练一次map值就下降到50%了这是什么原因？我用的google colab训练的，因为之前把数据下载到了本地，今天重新上传到colab再训练就成这样了，大佬们这是什么原因？

请问你在训练自己的数据时，是使用作者提供的预训练模型进行参数初始化的吗

**Comment by wl4135** [comment]
> > 我原先训练测试过一批数据，map在90%，但是什么参数也没改，数据也没变再训练一次map值就下降到50%了这是什么原因？我用的google colab训练的，因为之前把数据下载到了本地，今天重新上传到colab再训练就成这样了，大佬们这是什么原因？
> 
> 请问你在训练自己的数据时，是使用作者提供的预训练模型进行参数初始化的吗

是的

**Comment by yifeichenNJ** [comment]
请问你有做过在修改yolo顶部模型的情况下，只导入部分权重的工作吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wanglei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 上午10:57
收件人:&nbsp;"YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;;
抄送:&nbsp;"陈逸飞"<641374881@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515)





   
我原先训练测试过一批数据，map在90%，但是什么参数也没改，数据也没变再训练一次map值就下降到50%了这是什么原因？我用的google colab训练的，因为之前把数据下载到了本地，今天重新上传到colab再训练就成这样了，大佬们这是什么原因？
  
请问你在训练自己的数据时，是使用作者提供的预训练模型进行参数初始化的吗
  
是的

**Comment by ylqi007** [comment]
@wl4135 你好，你用作者提供的预训练模型是训练或测试的时候，有没有做修改？如果有修改，都做了哪些修改？

我也用作者的源代码训练的时候，mAP只有 44.82%，没有90%那么高过

**Comment by wl4135** [comment]
> @wl4135 你好，你用作者提供的预训练模型是训练或测试的时候，有没有做修改？如果有修改，都做了哪些修改？
> 
> 我也用作者的源代码训练的时候，mAP只有 44.82%，没有90%那么高过

没有刻意做什么修改，使用的是与训练模型训练的    使用作者的源码训练的在86左右%，自己的数据增强后使用聚类算法改了锚点框的尺寸大概map在94%左右   一个类别

**Comment by yifeichenNJ** [comment]
请问你有尝试过修改网络结构吗，修改了网络结构后如何一层一层的导入预训练权重




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wanglei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 下午4:05
收件人:&nbsp;"YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;;
抄送:&nbsp;"陈逸飞"<641374881@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515)





  
@wl4135 你好，你用作者提供的预训练模型是训练或测试的时候，有没有做修改？如果有修改，都做了哪些修改？
 
我也用作者的源代码训练的时候，mAP只有 44.82%，没有90%那么高过
  
没有刻意做什么修改，使用的是与训练模型训练的    使用作者的源码训练的在86左右%，自己的数据增强后使用聚类算法改了锚点框的尺寸大概map在94%左右   一个类别

**Comment by robinjoe93** [comment]
> > @wl4135 你好，你用作者提供的预训练模型是训练或测试的时候，有没有做修改？如果有修改，都做了哪些修改？
> > 我也用作者的源代码训练的时候，mAP只有 44.82%，没有90%那么高过
> 
> 没有刻意做什么修改，使用的是与训练模型训练的 使用作者的源码训练的在86左右%，自己的数据增强后使用聚类算法改了锚点框的尺寸大概map在94%左右 一个类别

麻烦问一下数据增强用的是什么方法额？我填了v4的数据增强，就没结果了。数据集20万张图片算少吗

**Comment by wl4135** [comment]
> > > @wl4135 你好，你用作者提供的预训练模型是训练或测试的时候，有没有做修改？如果有修改，都做了哪些修改？
> > > 我也用作者的源代码训练的时候，mAP只有 44.82%，没有90%那么高过
> > 
> > 
> > 没有刻意做什么修改，使用的是与训练模型训练的 使用作者的源码训练的在86左右%，自己的数据增强后使用聚类算法改了锚点框的尺寸大概map在94%左右 一个类别
> 
> 麻烦问一下数据增强用的是什么方法额？我填了v4的数据增强，就没结果了。数据集20万张图片算少吗

我用的是线下数据增强   增强完了又标注的   就是一些基本的增强  裁剪旋转之类的    之前试过标注后再增强  但是制作数据集的时候出错了   你的20万不少了    我的才几千张

**Comment by wl4135** [comment]
> 请问你有尝试过修改网络结构吗，修改了网络结构后如何一层一层的导入预训练权重
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"wanglei"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月11日(星期四) 下午4:05 收件人:&nbsp;"YunYang1994/tensorflow-yolov3"<tensorflow-yolov3@noreply.github.com&gt;; 抄送:&nbsp;"陈逸飞"<641374881@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [YunYang1994/tensorflow-yolov3] 训练测试 (#515) @wl4135 你好，你用作者提供的预训练模型是训练或测试的时候，有没有做修改？如果有修改，都做了哪些修改？ 我也用作者的源代码训练的时候，mAP只有 44.82%，没有90%那么高过 没有刻意做什么修改，使用的是与训练模型训练的 使用作者的源码训练的在86左右%，自己的数据增强后使用聚类算法改了锚点框的尺寸大概map在94%左右 一个类别 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没有修改过网络结构

**Comment by Kazusa853** [comment]
你好，请问我把在本地标记好的图片上传到colab进行训练，但xml文件里的path标签仍然是本地路径是否会有影响

**Comment by wl4135** [comment]
不会，我之前没出现什么问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kazusa853 <notifications@github.com&gt;
发送时间: 2020年7月18日 11:08
收件人: YunYang1994/tensorflow-yolov3 <tensorflow-yolov3@noreply.github.com&gt;
抄送: wanglei <1804068@mails.ccu.edu.cn&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[YunYang1994/tensorflow-yolov3] 训练测试 (#515)

**Comment by MuhammadAsadJaved** [comment]
> Have you encountered the problem of training loss = nan? I trained 20 times in the first stage, 2000 in the second stage, 4200 training pictures, and 800 test pictures, but I encountered the problem of test -loss = nan when I trained to 24 times, and the boss solved it.
> ![image](https://user-images.githubusercontent.com/40144255/79933076-8679d380-8481-11ea-9db6-2a4300c3b9fe.png)

Hi, I have the same problem , I am training 1 class, the test loss is always  NAN and training loss is NAN after few iterations. What is the possible reason?
