### ISSUE TITLE
ValueError: cannot reshape array of size 3549 into shape (6)

### ISSUE THREAD

**Issue by hexin6688** [YunYang1994/tensorflow-yolov3#518]
Traceback (most recent call last):
  File "G:/数据集/tensorflow-yolov3-master/image_demo.py", line 43, in <module>
    np.reshape(pred_lbbox, (-1, 5 + num_classes))], axis=0)
  File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "G:\anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 3549 into shape (6)

**Comment by alexanderDuenas** [comment]
I have the same problem, any solution???
