### ISSUE TITLE
IndexError: index 5 is out of bounds for axis 0 with size 5

### ISSUE THREAD

**Issue by yy4893** [YunYang1994/tensorflow-yolov3#531]
Hello,

First of all, thank you so much for sharing this useful code.

I have completed learning the YOLO model using VOC dataset.

And I got the following error while I was learning using my data.

Can you help me?

"C:\Users\GiYong KIM\Anconda3\envs\YOLO_Last\python.exe" "C:/Users/GiYong KIM/Desktop/Deep learning/YOLO_Last/Yunyang/train.py"
2020-05-13 10:56:34.276456: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-05-13 10:56:34.416017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.725
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.59GiB
2020-05-13 10:56:34.416247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2020-05-13 10:56:34.762370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-13 10:56:34.762505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2020-05-13 10:56:34.762585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2020-05-13 10:56:34.762765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6323 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
=> Restoring weights from: ./checkpoint/yolov3_coco_demo.ckpt ... 
  0%|          | 0/89 [00:00<?, ?it/s][0. 0. 1. 0. 0.]
[0. 0. 0. 0. 1.]
[0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0.]
train loss: 1454.72:   1%|          | 1/89 [00:05<08:14,  5.62s/it][0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]
[0. 1. 0. 0. 0.]
train loss: 3066.29:   2%|▏         | 2/89 [00:06<06:10,  4.26s/it][0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]
[1. 0. 0. 0. 0.]
train loss: 2669.98:   3%|▎         | 3/89 [00:07<04:42,  3.28s/it][0. 1. 0. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
train loss: 1189.81:   4%|▍         | 4/89 [00:08<03:34,  2.52s/it][0. 0. 1. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1.]
Traceback (most recent call last):
  File "C:/Users/GiYong KIM/Desktop/Deep learning/YOLO_Last/Yunyang/train.py", line 187, in <module>
    if __name__ == '__main__': YoloTrain().train()
  File "C:/Users/GiYong KIM/Desktop/Deep learning/YOLO_Last/Yunyang/train.py", line 147, in train
    for train_data in pbar:
  File "C:\Users\GiYong KIM\Anconda3\envs\YOLO_Last\lib\site-packages\tqdm\std.py", line 1119, in __iter__
    for obj in iterable:
  File "C:\Users\GiYong KIM\Desktop\Deep learning\YOLO_Last\Yunyang\core\dataset.py", line 84, in __next__
    label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes = self.preprocess_true_boxes(bboxes)
  File "C:\Users\GiYong KIM\Desktop\Deep learning\YOLO_Last\Yunyang\core\dataset.py", line 207, in preprocess_true_boxes
    onehot[bbox_class_ind] = 1.0
IndexError: index 5 is out of bounds for axis 0 with size 5
train loss: 1189.81:   4%|▍         | 4/89 [00:08<03:04,  2.17s/it]

Process finished with exit code 1

**Comment by Praneeth-AR** [comment]
Hey, I am facing the same issue and was wondering if you were able to solve it ?
