### ISSUE TITLE
自己的模型在测试时框框超出10647，超出的数字跟随图片变化，请问怎么修改

### ISSUE THREAD

**Issue by SettleSun** [YunYang1994/tensorflow-yolov3#62]
Traceback (most recent call last):
File "quick_test.py", line 33, in 
boxes, scores, labels = utils.cpu_nms(boxes, scores, num_classes, score_thresh=0.3, iou_thresh=0.5)
File "I:\PythonWorkspace\cetc_image_2_class_001\core\utils.py", line 122, in cpu_nms
filter_boxes = boxes[indices]
IndexError: index 22673 is out of bounds for axis 0 with size 10647

**Comment by Andy546** [comment]
please check the NUM_CLASSES

**Comment by SettleSun** [comment]
预测的时候修改python3 convert_weight.py -cf ./checkpoint/yolov3.ckpt-2000 -nc 8 -ap ./data/raccoon_anchors.txt --freeze中 -nc 的值等于你的分类总数
